### ISSUE TITLE
port is dropped

### ISSUE THREAD

**Issue by Nemo64** [colorcube/auto404#2]
This extension currently does not work if the domain name contains a port. I'd need that for local development.

**Comment by colorcube** [comment]
How do you configure the port for your site?

**Comment by Nemo64** [comment]
well it's basically my local dev machine (using docker) and i use `localhost:5000` as a domain name.

I found 2 places which would need to be adjusted in order for this to work.

-  https://github.com/colorcube/auto404/blob/4abe929a19e084bdd17d399534cd9a28f159d0e6/Classes/Hooks/FrontendHook.php#L119 here `TYPO3_HOST_ONLY` should be `HTTP_HOST`.
- https://github.com/colorcube/auto404/blob/b8821ab83436eb9602d4a71fbe5a453dde26e30d/Classes/Service/PageService.php#L78 here the hostname is exploded again... probably to remove the port too?

Well if I adjust both parts it works locally but i haven't tested it further yet.

**Comment by colorcube** [comment]
Thanks for the investigation. HTTP_HOST is used now. The domain check is done a bit differently now and works with ports.
Could you please try out the git version if it works for you?

**Comment by colorcube** [comment]
Version 1.1.0 released
