### ISSUE TITLE
Dependency to SimulateStaticUrls

### ISSUE THREAD

**Issue by ghost** [colorcube/auto404#3]
In some cases I get the error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'Colorcube\SimulateStaticUrls\Service\FrontendControllerService' not found | Error thrown in file /.../typo3conf/ext/auto404/Classes/Service/PageService.php in line 63. Requested URL: ...

So there is a dependecy to SimulateStaticUrls which is not documented (as far I can see). Furthermore I'm using RealUrl and I do not know if I should install SimulateStaticUrls and RealUrl at the same time.

**Comment by colorcube** [comment]
Thank's for reporting that bug. I'll have a look.

> if I should install SimulateStaticUrls and RealUrl at the same time.

No, don't do that!

**Comment by colorcube** [comment]
fixed in 1.1.1

**Comment by ghost** [comment]
That's what I a call a quick resposne and thanks for fixing it!
